# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Address', models.CharField(max_length=264)),
                ('Items', models.CharField(max_length=264)),
            ],
        ),
    ]
